/**
 * VintStack Core Type Definitions
 * 
 * Provides types for multi-modal listing inputs, normalized listing outputs,
 * provider configurations, and platform-specific formatters.
 */

/**
 * Image representation compatible with both browser (File/base64) and Node.js (Buffer/base64).
 */
export interface ImageInput {
  /** Base64-encoded image data without the data:image/...;base64, prefix */
  data: string;
  /** MIME type, e.g. 'image/jpeg', 'image/png', 'image/webp' */
  mimeType: string;
  /** Optional file name or label for reference */
  fileName?: string;
}

/**
 * Normalized input passed into the AI listing generator.
 */
export interface ListingInput {
  /** Array of product images (front, back, label, details, flaws) */
  images?: ImageInput[];
  /** Optional hint or tentative title provided by user */
  titleHint?: string;
  /** Optional seller notes (measurements, where purchased, defect details) */
  notes?: string;
  /** Optional brand override or hint */
  brandHint?: string;
  /** Expected item condition if known beforehand */
  conditionHint?: VintedCondition;
  /** Desired target language for title and description (defaults to Italian/English or auto-detect) */
  language?: 'it' | 'en' | 'fr' | 'es' | 'de' | 'auto';
  /** Platform target (defaults to 'vinted') */
  platform?: 'vinted' | 'depop' | 'ebay';
}

/**
 * Official Vinted condition categories.
 */
export type VintedCondition =
  | 'new_with_tags'
  | 'new_without_tags'
  | 'very_good'
  | 'good'
  | 'satisfactory';

/**
 * Price recommendation breakdown with reasoning.
 */
export interface PriceRecommendation {
  /** Recommended listing price (in EUR) */
  suggested: number;
  /** Minimum floor price (for quick sale or counter-offers) */
  min: number;
  /** High price ceiling (room for bargaining or rare vintage pieces) */
  max: number;
  /** Currency code (defaults to 'EUR') */
  currency: string;
  /** Concise reasoning behind the price based on brand and condition */
  reasoning: string;
}

/**
 * Normalized listing result generated by the AI model.
 */
export interface ListingResult {
  /** Optimized Vinted search title (concise, brand + item + size + condition) */
  title: string;
  /** Complete buyer-friendly description with sections for condition, fit, and details */
  description: string;
  /** Normalized category (e.g., 'Women > Tops > Blouses') */
  category: string;
  /** Detected or confirmed brand name */
  brand: string;
  /** Normalized size (e.g., 'M / 38 / 10', '42 EU', 'One Size') */
  size: string;
  /** Standardized condition */
  condition: VintedCondition;
  /** Dominant color(s) */
  color: string;
  /** Primary material / fabric (e.g., '100% Cotton', 'Wool blend', 'Denim') */
  material: string;
  /** Price recommendation */
  price: PriceRecommendation;
  /** High-ranking searchable hashtags (e.g. ['#vintage', '#y2k', '#zara']) */
  hashtags: string[];
  /** Noted imperfections or flaws disclosed for buyer trust */
  flaws: string[];
  /** Measurement guidelines or estimated fit (e.g. 'Fits true to size') */
  fitNotes: string;
  /** Model confidence score between 0.0 and 1.0 */
  confidence: number;
  /** Timestamp of generation */
  createdAt: string;
}

/**
 * Formatted output ready for clipboard copy or platform export.
 */
export interface FormattedListing {
  /** Title ready for direct paste */
  title: string;
  /** Formatted multiline description with disclaimer, specs, and hashtags */
  description: string;
  /** Formatted tags line */
  tagsText: string;
  /** Price string (e.g. '25.00') */
  priceString: string;
  /** Complete bundle text combining all fields */
  fullBundleText: string;
  /** Clean markdown table representation ready for 1-click copying */
  tableMarkdown: string;
}

/**
 * Provider-agnostic interface for AI listing generation.
 */
export interface AIProvider {
  /** Unique provider identifier (e.g. 'gemini', 'openai', 'anthropic', 'ollama') */
  readonly id: string;
  /** Human-readable provider display name */
  readonly name: string;

  /**
   * Generates a normalized listing from image and text inputs.
   */
  generateListing(input: ListingInput, config: ProviderConfig): Promise<ListingResult>;

  /**
   * Validates whether the API key or endpoint is reachable and authenticated.
   */
  testConnection(config: ProviderConfig): Promise<{ success: boolean; message: string }>;
}

/**
 * Configuration options for AI providers.
 */
export interface ProviderConfig {
  /** API key (BYOK) */
  apiKey: string;
  /** Optional custom model name (e.g., 'gemini-2.5-flash', 'gemini-1.5-pro') */
  model?: string;
  /** Optional custom base URL (useful for self-hosted Ollama or proxies) */
  baseUrl?: string;
  /** Optional timeout in milliseconds */
  timeoutMs?: number;
}
